### ISSUE TITLE
UI Sound in the menu doesn't update automatically

### ISSUE THREAD

**Issue by raxp122** [echo-lalia/MicroHydra#181]
If i click the OK button when i'm on UI SOUND in the menù the setting is updated but it doesn't update the label on screen it unless i move to another menu entry and go back to the sound one

**Comment by raxp122** [comment]
I'm on MH2.3

**Comment by echo-lalia** [comment]
Darn, I thought I fixed this issue already, but apparently not (or I broke it again, lol).
