### ISSUE TITLE
Is there a way to exit app without pressing reset btn?

### ISSUE THREAD

**Issue by TheBricktop** [echo-lalia/MicroHydra#61]
Same question as in title.
Tried pressing all buttons but ive not came across a right combination.

**Comment by echo-lalia** [comment]
Apps need to add their own method of closing to make that possible. 

Most of the built in apps (maybe all of them?) allow you to return home with a press of the ESC key or G0 key, but the reset button is the only way to get home from an app that doesn't implement that functionality.

**Comment by echo-lalia** [comment]
I just want to add; I plan on adding a 'universal' exit shortcut to a future version of the Keyboard module :)

**Comment by TheBricktop** [comment]
Thank you for your answer.
